export const TYPES = {
    ADD_NEW_TODO:'ADD_NEW_TODO',
    TOOGLE_COMPLETE_TODO:'TOOGLE_COMPLETE_TODO',
    DELETE_TODO:'DELETE_TODO',
    REORDER_TODOS:'REORDER_TODOS',
    CLEAR_COMPLETED_TODOS:'CLEAR_COMPLETED_TODOS',
    EDIT_TEXT_TODO:'EDIT_TEXT_TODO',
    FETCH_DATA_FROM_LOCALSTORAGE:'FETCH_DATA_FROM_LOCALSTORAGE:',
    SELECT_FILTER:' SELECT_FILTER'
}